config/routes.rb
Rails.application.routes.draw do

  resources :carts, except: [:index, :new, :edit]
  resources :join_table_items_carts, only: [:create, :update, :destroy]
  resources :items
  root to: "items#index"
  devise_for :users

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user, optional: true
  has_many :join_table_items_carts, dependent: :nullify
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :join_table_items_carts, dependent: :nullify
  # nullify va nous permettre d’effacer des entrées dans la table « join_table_items_carts » sans faire apparaître une erreur
end

app/models/join_table_items_cart.rb
class JoinTableItemsCart < ApplicationRecord
  belongs_to :item
  belongs_to :cart

  def self.add_or_create_cart_item_link(permit_link_params)
  	if JoinTableItemsCart.find_by(cart_id: permit_link_params[:cart_id], item_id: permit_link_params[:item_id]) == nil
  		@new_item_add = JoinTableItemsCart.create(item_id: permit_link_params[:item_id], cart_id: permit_link_params[:cart_id], quantity: 1)
  	else
  		@new_item_add = JoinTableItemsCart.find_by(cart_id: permit_link_params[:cart_id], item_id: permit_link_params[:item_id])
  		@new_item_add.update(quantity: @new_item_add.quantity + 1)
  	end
  end
  #consiste à vérifier l’existence de l’article dans le panier de l’utilisateur connecter 
  #et si il existe alors il ajoute un 1 à la quantité, 
  #sinon il crée une nouvelle entrée dans la base de données « JoinTableItemsCart » associant l’article et mon panier »
  
end

app/models/user.rb
class User < ApplicationRecord
  has_one :cart
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  after_create :welcome_send
  
  def welcome_send
      UserMailer.welcome_email(self).deliver_now
  end       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  after_action :create_cart_and_assign_to_current_user, only: [:create]
end

#la 1ere ligne on créé un lien entre le controller d’application. 
#La 2e fait appel à la méthode « create_cart_and_assign_to_current_user » seulement après une méthode « create ».

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include CartsHelper
  before_action :require_login
  before_action :only_current_cart

  def show
    @items_in_cart = JoinTableItemsCart.where(cart_id:current_user.cart.id)
  end
  #trouves-moi les entrées où le panier utilisé est le même que celui de la personne connecté puis enregistre tout ça dans la variable « @items_in_cart ». 
  #

  def create
  end

  def update
  end

  def destroy
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
    def create
        @total = params[:total].to_d
        @session = Stripe::Checkout::Session.create(
          payment_method_types: ['card'],
          line_items: [
            {
              price_data: {
                currency: 'eur',
                unit_amount: (@total*100).to_i,
                product_data: {
                  name: 'Rails Stripe Checkout',
                },
              },
              quantity: 1
            },
          ],
          mode: 'payment',
          success_url: checkout_success_url + '?session_id={CHECKOUT_SESSION_ID}',
          cancel_url: checkout_cancel_url
        )
        redirect_to @session.url, allow_other_host: true
    end
    
    def success
        @session = Stripe::Checkout::Session.retrieve(params[:session_id])
        @payment_intent = Stripe::PaymentIntent.retrieve(@session.payment_intent)
    end
    
    def cancel
    end

    def process_payment
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]
  before_action :check_admin_role, only: %i[edit update destroy]
  include ItemsHelper
  before_action :save_items_in_cart

  # GET /items or /items.json
  def index
    @items = Item.all
    @join_table_item_cart = JoinTableItemsCart.new
  end

  # GET /items/1 or /items/1.json
  def show
    @item = Item.find(params[:id])
    @join_table_item_cart = JoinTableItemsCart.new
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)
    
    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_url(@item), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:title, :description, :price, :image_url)
    end

    def check_admin_role
      unless current_user && current_user.role == "admin"
        redirect_to root_path, alert: "Vous n'avez pas les autorisations nécessaires pour accéder à cette page."
      end
    end
end

app/controllers/join_table_items_carts_controller.rb
class JoinTableItemsCartsController < ApplicationController
  
  def create
    @item_add = JoinTableItemsCart.add_or_create_cart_item_link(permit_link_params)
    redirect_to items_path
  end

  def update
  end

  def destroy
    puts "$" *100
    puts params[:id]
    puts "$" *100
    @item_delete = JoinTableItemsCart.find(params[:id])
    @item_delete.destroy
    redirect_to cart_path #(current_user.cart.id)
  end

  private

  def permit_link_params
    params.require(:join_table_items_cart).permit(:item_id, :cart_id, :quantity)
  end

  #les informations envoyées par le formulaire par « params » soient autorisées à être utilisé

end

app/helpers/application_helper.rb
module ApplicationHelper

  def create_cart_and_assign_to_current_user
    if current_user != nil && current_user.cart == nil
        cart = Cart.create(user: current_user)
    end
  end

  def add_zero(price)
    price_str = price.to_s
    if price_str.split('.').last.size < 2
      price_str.insert((price_str.length),'0')
    end
    return price_str
  end
end

# Si on a une session utilisateur en cours et que celui-ci n’a pas de panier qui lui est assigné. 
#Créés-en un et assignes lui » 

app/helpers/carts_helper.rb
module CartsHelper
  
  private

  def require_login
      unless current_user != nil
          redirect_to new_user_session_path
      end
  end

  def only_current_cart
    if current_user != nil && current_user.cart.id != params[:id].to_i
        return redirect_to cart_path(current_user.cart.id)
    end
  end

end

#require_login : S'il n’y a personne de connecté, rediriger la page vers la page de connexion
#only_current_cart empêchera les personnes connectées de se rendre (via l’URL entre autres) sur un panier qui n’est pas le leur

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  def save_items_in_cart
    if current_user != nil
        @items_in_cart = JoinTableItemsCart.where(cart_id:current_user.cart.id)
    end
  end
end

app/helpers/join_table_items_carts_helper.rb
module JoinTableItemsCartsHelper
end

app/views/carts/create.html.erb
<h1>Carts#create</h1>
<p>Find me in app/views/carts/create.html.erb</p>

app/views/carts/destroy.html.erb
<h1>Carts#destroy</h1>
<p>Find me in app/views/carts/destroy.html.erb</p>

app/views/carts/show.html.erb
<br/>
<div class="container">
    <h1>My Cart</h1>
    <br/>
    <br/>
        <div class="row">
            <div class="col-lg-8 col-md-8">
                <table class="table">
                    <thead>
                        <tr>
                        <th scope="col">Quantity</th>
                        <th scope="col">Articles</th>
                        <th scope="col">Price</th>
                        <th scope="col">Price by quantity</th>
                        <th scope="col"></th>

                        </tr>
                    </thead>
                    <tbody>
                        <% total_price = [] %>
                        <%  @items_in_cart.each do |item| %>
                            <tr>
                            <th scope="row"><%= item.quantity %></th>
                            <td><%= item.item.title %></td>
                            <td><%= item.item.price %>€</td>
                            <td><%= total_item = item.item.price*item.quantity.to_d %>€</td>
                            <% total_price << total_item %>
                            <td><%= button_to "delete this item", join_table_items_cart_path(item.id), method: :delete, class: 'btn btn-danger' %>
                            </td>
                        <% end %>
                         <tr>
                            <th scope="row"></th>
                            <td></td>
                            <td></td></td>
                            <td></td>
                            </tr>
                            <tr>
                            <th scope="row"></th>
                            <td></td>
                            <td class="font-weight-bold">Total:</td>
                            <td><%= total_price.inject(0){|sum,x| sum + x }%>€</td>
                         </tr>
                    </tbody>
                </table>
                <%= button_to "Click Here to pay", checkout_create_path(total: total_price.inject(0){|sum,x| sum + x }), class: "btn btn-primary center-button", data: {turbo: false} %>
            </div>
        </div>
</div>

<%# Ajoutez le prix selon quantité dans l’array vide : « <% total_price << total_item %>
<%# additionne tout les prix présents à l’intérieur et j’affiche le résultat:  » <%= total_price.inject(0){|sum,x| sum + x }%>

app/views/carts/update.html.erb
<h1>Carts#update</h1>
<p>Find me in app/views/carts/update.html.erb</p>

app/views/checkout/cancel.html.erb
<div class="container text-center my-5"> 
    <h1>Echec</h1> 
    <p>Le paiement n'a pas abouti.</p>
</div> 

app/views/checkout/success.html.erb
<div class="container text-center my-5"> 
    <h1>Succès</h1> 
    <p>Nous avons bien reçu votre paiement de <%= number_to_currency(@payment_intent.amount_received / 100.0, unit: "€", separator: ",", delimiter: "", format: "%n %u") %>.</p> 
    <p>Le statut de votre paiement est : <%= @payment_intent.status %>.</p> 
</div>

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :image_url, style: "display: block" %>
    <%= form.text_field :image_url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/items/_item.html.erb
<div id="<%= dom_id item %>" class="row">
  <div class="col-md-6">
    <%= image_tag item.image_url, class: 'img-thumbnail custom-img-size' %>
  </div>
  <div class="col-md-6">
    <strong>Title:</strong>
    <%= item.title %>
    <p></p>
    <strong>Description:</strong>
    <%= item.description %>
    <p></p>
    <strong>Price:</strong>
    <%= add_zero(item.price) %>
    <p></p>
    <% if user_signed_in? %>
      <%= form_for @join_table_item_cart do |f| %>
        <%= f.hidden_field :item_id, value: @item.id %>
        <%= f.hidden_field :cart_id, value: current_user.cart.id %>
        <button type="submit" class="btn btn-success">Ajouter au panier</button>
      <% end %>
    <% end %>
  </div>
</div>

app/views/items/_listCard.html.erb
<div id="<%= dom_id item %>">
    <div class="card pb-3 mb-5 rounded-5 mx-3"  style="width: 23rem;">
        <%=image_tag item.image_url,:class=>"w-100 rounded-top-5 list_img"%>
        <div class="p-2 card-body d-flex flex-column align-items-around justify-content-between">
        <h5 class="card-title text-center"><%= item.title %></h5>
        <p class="card-text"> <%= item.description %></p>
        <p class="card-text"> <%= add_zero(item.price) %> €</p>
        <%= link_to "Show this item", item,:class=>"btn btn-outline-primary justify-content-center align-items-center" %>
        </div>
    </div>
</div>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Show this item", @item %> |
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/index.html.erb
<p style="color: green"><%= notice %></p>

<main class="container container-xs-fluid">
        <section>
           <h2>Our cute Kitten</h2>

<div id="items" class="d-flex flex-wrap justify-content-around">
  <% @items.each do |item| %>
    <%= render "items/listCard",item: item %>
  <% end %>
</div>
        </section>
        <section id="contact" class="py-5">
            <div class="container">
                <h2 class="mb-0">Any questions ?</h2>
                <h3 class="fw-light fs-5">Contact us here</h3>

                <div class="row gy-4  d-flex align-items-center justify-content-between">
                    <div class="col-12 col-md-5">
                        <img src="https://www.zooplus.fr/magazine/wp-content/uploads/2018/02/fotolia_82719975-1.jpg" alt="Contact" width="100%">
                    </div>
                    <div class="col-12 offset-md-1 col-md-6">

                        <!-- Formulaire -->
                        <form class="row">
                            <div class="col-12 my-2">
                                <label for="email" class="form-label">Email address</label>
                                <input name="email" type="email" class="form-control" id="email">
                            </div>
                            <div class="col-12 my-2">
                                <label for="message" class="form-label">Message</label>
                                <textarea name="message" class="form-control" id="message" rows="3"></textarea>
                            </div>
                            <div class="col-12 my-2">
                                <button type="submit" class="btn btn-primary w-100">Envoyer</button>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </section>
    </main>
<% if user_signed_in? && current_user.role === 'admin' %>
<ul>
 <li>
   <%= link_to "New item", new_item_path %>
 </li>
</ul>
<%end%>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @item %>

<div></div>




<% if user_signed_in? && current_user.role === 'admin' %>
    <%= link_to "Edit this item", edit_item_path(@item) %> |
    <%= link_to "Back to items", items_path %>
  <%= button_to "Destroy this item", @item, method: :delete %>
<%end%>

  

app/views/join_table_items_carts/create.html.erb
<h1>JoinTableItemsCarts#create</h1>
<p>Find me in app/views/join_table_items_carts/create.html.erb</p>

app/views/join_table_items_carts/destroy.html.erb
<h1>JoinTableItemsCarts#destroy</h1>
<p>Find me in app/views/join_table_items_carts/destroy.html.erb</p>

app/views/join_table_items_carts/update.html.erb
<h1>JoinTableItemsCarts#update</h1>
<p>Find me in app/views/join_table_items_carts/update.html.erb</p>

app/views/layouts/_footer.html.erb
<div class="footer bg-dark">
<!-- Section: Social media -->
<section class="d-flex justify-content-between p-1" style="background-color: rgba(0, 0, 0, 0.2)">
    <!-- Left -->
    <div class="me-5">
    <span>Stay connected on our social networks :</span>
    </div>
    <!-- Left -->

    <!-- Right -->
    <div>
    <a href="#" class=" me-2 text-decoration-none">
        <i class="fab fa-facebook-f"></i>
    </a>
    <a href="" class=" me-2 text-decoration-none">
        <i class="fab fa-twitter"></i>
    </a>
    <a href="" class=" me-2 text-decoration-none">
        <i class="fab fa-instagram"></i>
    </a>
    <a href="" class=" me-2 text-decoration-none">
        <i class="fab fa-linkedin"></i>
    </a>
    <a href="" class=" me-2 text-decoration-none">
        <i class="fab fa-github"></i>
    </a>
    </div>
    <!-- Right -->
</section>
<!-- Section: Social media -->

<!-- Section: Links  -->
<section class="">
    <div class="container text-center text-md-start ">
    <!-- Grid row -->
    <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
        <!-- Content -->
        <p class="text-uppercase fw-bold">Kittenshop</p>
        <hr class="mb-1 mt-0 d-inline-block mx-auto">
        <p>
            KittenShop is an interactive platform that allows you to buy kitten images</p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-3">
        <!-- Links -->
        <h6 class="text-uppercase fw-bold">Products</h6>
        <hr class="mb-1 mt-0 d-inline-block mx-auto">
        <p>
            <a href="#!" class="text-decoration-none">MDBootstrap</a>
        </p>
        <p>
            <a href="#!" class="text-decoration-none">MDWordPress</a>
        </p>
        <p>
            <a href="#!" class="text-decoration-none">BrandFlow</a>
        </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-3">
        <!-- Links -->
        <h6 class="text-uppercase fw-bold">Useful links</h6>
        <hr class="mb-1 mt-0 d-inline-block mx-auto">
        <p>
            <a href="#!" class="text-decoration-none">Your Account</a>
        </p>
        <p>
        <a href="#!" class="text-decoration-none">Shipping Rates</a>
        </p> 
        <p>
              <a href="#!" class="text-decoration-none">Become an Affiliate</a>
        </p>
       
        <p>
            <a href="#!" class="text-decoration-none">Help</a>
        </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
        <!-- Links -->
        <h6 class="text-uppercase fw-bold">Contact</h6>
        <hr class="mb-1 mt-0 d-inline-block mx-auto">
        <p><i class="fas fa-home mr-3"></i> Boulogne-Billancourt, 92100, FR</p>
        <p><i class="fas fa-envelope mr-3"></i> kittenshop@gmail.com</p>
        <p><i class="fas fa-phone mr-3"></i> + 06 01 02 03 04</p>
        </div>
        <!-- Grid column -->
    </div>
    <!-- Grid row -->
    </div>
</section>
<!-- Section: Links  -->

<!-- Copyright -->
<div
    class="text-center p-3"
    style="background-color: rgba(0, 0, 0, 0.2)"
    >
    © 2023 Copyright : 
    <a class="text-decoration-none" href="https://mdbootstrap.com/"
    > KittenShop.com</a
    >
</div>
<!-- Copyright -->
</div>

app/views/layouts/_header.html.erb
    <nav class="navbar navbar-expand-lg bg-light mb-5 fs-6 p-2" data-bs-theme="light">
            <div class="container-fluid">
            <a class="navbar-brand fs-5" href="<%= root_path %>">Kittenshop</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor03">
                <div class="">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link active" href="<%= root_path %>">Home
                            <span class="visually-hidden">(current)</span>
                            </a>
                        </li>    
                    </ul>
                </div>
                <div>
                    <ul class="navbar-nav me-3">
                        <li class="nav-item ">
                          

                        </li>
                        <li class="nav-item dropdown">
                        <% if user_signed_in? %>
                        <%# bouton du panier %>
                          
                         
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Log out</a>
                            
                            <div class="dropdown-menu">
                            
                                <!-- Le contenu à afficher lorsque la session est active -->
                                <%= button_to "Déconnexion", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                            
                            <li class="nav-item">
                             <a class="nav-link" href="<%= cart_path(current_user.cart.id) if current_user %>">
                            <i class="fas fa-shopping-cart"></i>
                            <% if @items_in_cart && @items_in_cart.count > 0 %>
                              <% total_items = []
                                  @items_in_cart.each do |item_choosed|
                                      item_quantity = item_choosed.quantity
                                      total_items << item_quantity
                                  end %>
                              <span class="badge badge-pill badge-info"><%= total_items.inject(0){|sum,x| sum + x }%></span>
                            <% else %>
                              <span class="badge badge-pill badge-info">0</span>
                            <% end %>
                          </a>
                          </li>
                            <% else %>
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Sign in / Sign up</a>
                            <div class="dropdown-menu">
                                <!-- Le contenu à afficher lorsque la session n'est pas active -->

                                        <a class="dropdown-item" href="<%= new_user_session_path %>">Log in</a>
                                        <a class="dropdown-item" href="<%=  new_user_registration_path %>">Sign up</a> 

                                                                             
                            <% end %>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
            </div>

        </nav> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KittenProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <%= stylesheet_link_tag 'bootstrap' %>    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script src="https://js.stripe.com/v3/"></script>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
  <header>
     <%= render 'layouts/header'%>
  </header>
  <%= yield %>
  <footer class="text-center text-lg-start bg-dark text-white ">
      <%= render 'layouts/footer'%>
  </footer >
  </body>
</html>